### ISSUE TITLE
Space characters in bsh.classpath.BshClassPath.getRTJarPath()

### ISSUE THREAD

**Issue by peetscott** [beanshell/beanshell#24]
This is probably a Windows specific issue.

Suppose java is located here

C:\Program Files\Java\jre1.8.0_91

getRTJarPath() returns this String:

/C:/Program%20Files/Java/jre1.8.0_91/lib/rt.jar

getBootClassPath() uses the String to create a URL from
a File (line 659). But
1. new File("/C:/Program%20Files/Java/jre1.8.0_91/lib/rt.jar")
   is not a valid File.
2. new File("/C:/Program%20Files/Java/jre1.8.0_91/lib/rt.jar").toURI()
   produces
   file:/C:/Program%2520Files/Java/jre1.8.0_91/lib/rt.jar
   which is a corrupt URI. toURI() wants to encode the '%' character
   without realizing that the space character has already been
   encoded. To be expected because File does not recognize encoded
   characters.

toURL() propagates the error.

searchJarForClasses() tries to URL.openStream() and it fails.

Try this:

cp = this.namespace.getClassManager().getClassPath();
cp.getClassSource("java.lang.Object");

It returns null.

---

Possible Solutions

(1.) Do

urlString.replaceAll("%20", " ");

before returning from getRTJarPath(). This handles encoded space characters in
the path. There could still be other encoded characters though.

(2.) Create the URL directly from getRTJarPath().

```
public static BshClassPath getBootClassPath() 
  throws ClassPathException  {
     ...
  URL url = new URL("file:" + getRTJarPath());
     ...
}
```

**Comment by darksidepuffin** [comment]
I just confirmed that your proposed fix fixes this on my Windows 10 box:

https://github.com/beanshell/beanshell/compare/master...darksidepuffin:master 

Seems overkill to submit a pull request for a one line change, though.

**Comment by nickl-** [comment]
I had to implement `jrtfs` to load Java 9 and Java 10 from `jrt:/java.base` via the module since rt.jar is no longer available.

At the same time I then also implemented loading classes from `rt.jar` via `jarfs` instead of recreating the jar file url again, which is what caused this bug it would seem.

`getRTJarPath()` now returns a URL which is basically the URL retrieved by `Class.class.getResource("/java/lang/String.class").toExternalForm();` minus `/java/lang/String.class` and then we use `FileSystems.getFileSystem(url.toURI())` to access the jar file.

see beanshell/beanshell@5d7aa05

@peetscott and @darksidepuffin  Please can you test this on Windows and see if it works as expected.

**Comment by nickl-** [comment]
Tested on Windows 10 with both JDK 1.8 and Java 10.
Can now successfully build and run.

Had to mark one unicode test as a known issue to be skipped, need to find out why.

Also doesn't help that classpath is still not covered with unit tests so this issue remains unchecked.

**Comment by nickl-** [comment]
Fixed unicode test to pass on Windows

**Comment by nickl-** [comment]
Tested on Windows 10
JDK 1.8 rt.jar is loaded
Java 10 jrt:/java.base module is loaded

Closed: Tested working
