### ISSUE TITLE
Bad exception received from inter.getInterface() proxy

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#240]
When you use bsh.Interpreter.getInterface\(xxx\), the 
proxy you receive will have distinct behaviour depending 
if the method that is called has a &amp;quot;throws&amp;quot; clause or not 
and if the method is not implemented by the script.

Imagine that you have this interface:

public interface IBla
\{
public void simple\(\);
public void comlex\(\) throws Exception\(\);
\}

and you create an Interpreter for an \*empty\* script \(not 
implementing any of the above methods\).

If you then do:
IBla proxy = \(IBla\)interpreter.getInterface \(IBla.class\);

Then:
proxy.simple\(\)

will throw an UndeclaredThrowableException 

While:
proxy.complex\(\)

will throw an bsh.EvalError which is a CHECKED 
exception. 

Consequently, in the second case, your code is not 
required \*at compile time\* to check for an exception 
while a \*checked\* exception will be thrown at \*runtime\*.

Reported by: slaboure

Original Ticket: "beanshell/bugs/102":https://sourceforge.net/p/beanshell/bugs/102

**Comment by opeongo** [comment]
I am not sure if this is an bug or not, possibly it is working as expected.

When calling through the proxy for the first undefined method the interpreter throws an EvalError for an undefined method.  Since no throws clause is specified on the interface the proxy wraps this exception in an UndeclaredThrowableException.  This seems correct as per the contract.

When calling through the proxy for the second undefined method the interpreter again throws an EvalError for an undefined method (which despite the name is a subclass of Exception).  Since the interface has a throws clause that specifies Exception, this can be passed through without wrapping.

I'm not sure what else is to be expected.  I don't think it is appropriate for the proxy handler to get in the way and do something like throwing a NoSuchMethod exception, since the invoke method could be the implementer and the EvalError could be real.

Attached is the original test case from SourceForge (slightly modified).


[ProxyTest.zip](https://github.com/beanshell/beanshell/files/3232523/ProxyTest.zip)

**Comment by nickl-** [comment]
@opeongo Would it be beneficial to add the test case but make it to pass as expected?

**Comment by opeongo** [comment]
Sure, I can do this if we agree that these are the expected semantics.

How else could it be handled?

**Comment by nickl-** [comment]
@opeongo  I agree with your assessment. Works as expected.

**Comment by nickl-** [comment]
**Closed: Works as expected**
