### ISSUE TITLE
Error when resolving ambiguous class names

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#32]
I noticed a problem when BeanShell tries to resolve ambiguous class names.  I will have to show a contrived example to demonstrate this in a simple way, but it does affect my application.  My actual actual situation is a bit too complication to show as an example, so please bear with the obvious non-standard naming that I will use to show the problem.

Imagine that I create a class named org.myorg.myapp.base.org.  (I realize that the classname of 'org' is unusual.)

Then I import this class in to the BeanShell interpreter:

```java
import org.myorg.myapp.base.*;
new org();
```

I also have a class named org.myorg.myapp.Gui.  If I try to invoke the main method from this class like so
```java
org.myorg.myapp.Gui.main(new String[0]);
```
the BeanShell interpreter will throw an error:
```
  'org.myorg.myapp.Gui.main(new String[0]); ' : No static field or inner class: myorg of class org.myorg.myapp.base.org
```
I had a look in the code and the problem is in the name resolving mechanism.  BeanShell will identify that the first part of the name (org) matches to a local known class (org.myorg.myapp.base.org), and will then try to resolve the rest of the name (myorg.myapp.Gui) relative to that class.

I think the problem is at line 292 in [Name.java](https://github.com/beanshell/beanshell/blob/master/src/main/java/bsh/Name.java).  I believe that the search for a matching class should be done in reverse order (all parts first, then take away one at a time), allowing for explicitly qualified classes to match before looking at fields within the class.

Any comment on this?  Is this the right change to make, or I am missing something here?

**Comment by nickl-** [comment]
TODO: Need unit tests see #72

**Comment by nickl-** [comment]
Java also won't allow this, it will generate a compilation error:

```
cannot find symbol 
symbol:   variable myorg
location: class org.myorg.myapp.base.org
```

The only way around this is to avoid the import of the conflicting name.

```java
new org.myorg.myapp.base.org();
org.myorg.myapp.Gui.main(new String[0]);
```

will work in java and also works in BeanShell.

Trying to find a class backwards will also have the same issue when there is a class with static members identical to a class within a package.

A quick example I can think off now.

```java
class org {
    static Integer val = 1;
}

package org;
class val {
  static Integer valueOf(in val) {}
}

org.val.valueOf(1);
```
Which valueOf method should we pick now? In java it will be the class named org, but with reverse class detection we will use the class named val.

Since BeanShell also attempts to be a java source interpreter it is best we stick within the java language constraints.

Closed: Won't fix, works as expected.
