### ISSUE TITLE
/*** ... comment ... **/ is misunderstood

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#322]
`/*** ... comment ... **/` is misunderstood in an `if ... else if ... else if` block.

For example, the following has syntactical error:
Parse error at line 7, column 1.  Encountered: else

```java
if (1 == 2)
print (1);
/***
This code is
commented
***/
else if (2 == 3)
print (2);
```
If the above code is rewritten as the following then it is ok:
```java
if (1 == 2)
print (1);
/*
This code is
commented
*/
else if (2 == 3)
print (2);
```

Thanks,

Binh

PS: My Environment is bsh 2.0beta 1, jsdk 1.4.2

Reported by: *anonymous

Original Ticket: "beanshell/bugs/184":https://sourceforge.net/p/beanshell/bugs/184

**Comment by nickl-** [comment]
Indeed so:

```java
// Error: Parser Error: Unable to parse code syntax. Encountered: else at line 10, column 1
```

**Comment by opeongo** [comment]
The comment
```java
/***
This code is
commented
***/
```
is by convention a formal comment since it starts with `/**`.  The problem showing up in this example is that this comment is located within a statement, and that does not make sense for a formal comment.  The beanshell grammar only allows formal comments to occur where they are expected, such as before class and method definitions.  So the problem is with the beanshell grammar assumption.

To fix this the parser will need to use lexical states to indicate where a `/**` comment should be parsed as a formal comment (such as where a class or method definition is possible) and elsewhere where is is interpreted as just a regular multiline comment.   When the grammar is amenable to accepting a formal comment the is should enable the lexical model to allow detection of formal comments and suppression of multiline comments.  When it is not at a place where it will accept formal comments then these rules are reversed.

**Comment by nickl-** [comment]
So what you are saying is that it is being picked up as a formal comment `/**` and not as a standard comment `/*` which should be acceptable anywhere.

**Comment by opeongo** [comment]
Yes, exactly.  The lexer detects it as a `<FORMAL_COMMENT>` token.  The grammar only allows formal comments to occur in specific places, so when it is detected in a place where it is not expected then semantic exception occurs.

As I said one way to fix this is by switching between several lexical states.  The `<FORMAL_COMMENT>` token can active in one state and deactive in the other.  Similarly there can be a complementary SKIP pattern that is inactive in one state and active in the other.  The tricks is setting up the jjt file to switch states correctly.  State switching usually happens when entering productions, but you can change them programmaticly as well.  Dealing with lookaheads can be tricky because the tokens are parsed under the current lexical state and if the lookahead does not match then tokens are pushed back on the stack as is and are not reparsed even if the lexical state changes.  So it might be tricky to do this right.

Another way to fix it would be to change the grammar to allow formal comments everywhere.  This approach sounds like a nightmare.

Perhaps there is simpler way to accomplish this using a lexical function.

**Comment by nickl-** [comment]
related to #753

**Comment by opeongo** [comment]
> related to #753

lol I completely forgot about this issue.  It's like going around in circles.

**Comment by nickl-** [comment]
> > related to #753
> 
> lol I completely forgot about this issue. It's like going around in circles.

Process of elimination =)
