### ISSUE TITLE
[question] could be beanshell replaced by JDK9 jshell?

### ISSUE THREAD

**Issue by archenroot** [beanshell/beanshell#34]
Hi, I like this project a lot, do you think the functionality will be all available in newly incoming jshell with JDK, or there is still more what beansheel could offer?

**Comment by broneill** [comment]
I've played around with jshell, and a couple of things irritate me. First, it takes about two seconds to launch the thing. Second, it has no type inference when assigning to a local variable. This means that I have to type the whole declaration, making jshell less convenient to use than just creating a new Java class and running that.

Jshell does offer a really bizarre "convenience" feature which allows the type declaration to be filled in for you automatically, like an IDE, by typing shift-<tab> v.  I'm pretty sure that the jshell designers never used beanshell. Otherwise, they'd truly love the convenience and speed it offers. Why throw that away?

Jshell does however auto assign $<num> variables when evaluating expressions that are assigned to a variable. Beanshell offers the $_ variable, but it has one slot. So I could have a whole pile of anonymous auto assigned variables, but with meaningless numbers instead of useful names.

I'll keep using Beanshell.

**Comment by nickl-** [comment]
Closed: answered

If you have more questions feel free to create a new issue.

**Comment by archenroot** [comment]
Yes, guys, thank you for answers I red those, but just didn't react. The question is clearly answered, thank you.

**Comment by nickl-** [comment]
@archenroot yw and ty for your participation =)
