### ISSUE TITLE
if-else does not consider line terminator

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#342]
```java
subject = "[vn-families] aaa";
if (subject.indexOf ("vn-families") >= 0 || subject.indexOf ("vmdd") >= 0 || subject.indexOf ("Vn-families post") >= 0)
    ; //Skip
else {
    print ("0");
}
```

will print "0" which is INCORRECT.

Binh

Reported by: *anonymous

Original Ticket: "beanshell/bugs/204":https://sourceforge.net/p/beanshell/bugs/204

**Comment by nickl-** [comment]
Can reproduce, if statement does not consider the line terminator `;`

**Comment by nickl-** [comment]
Additional symptoms from not considering line terminator:

bsh 1.2b7, bsh 2.0beta, and possibly all bsh versions
gave wrong result for the following:
```java
a = 2;
if (a == 1)
;
else if (a == 2)
a = 22;
else
a = 33;

System.out.println (a); //print 2 instead of 22
```
To circumvent this bug, I use a dummy statement
instead of an empty one. Example:
```java
a = 2;
if (a == 1)
0;
else if (a == 2)
a = 22;
else
a = 33;

System.out.println (a); //print 22 which is correct
```
PS: By the way, when will the next version come
out? Thanks.

Ben

Reported by: binhph

Original Ticket: "beanshell/bugs/165":https://sourceforge.net/p/beanshell/bugs/165
