### ISSUE TITLE
Ambigous class names after "import *"

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#401]
Dear Sir,

I found BeanShell is very useful for my current
development in Java. But I got a small problem after
using the command "import \*". After that, every
operation related to the "String" object will be
complained with the error:

Ambigous class names:
\[com.sun.org.apache.xpath.internal.operations.String,
java.lang.String\]

I am using jdk1.5.0\_07. Here after is my example:
\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
BeanShell 2.0b4 - by Pat Niemeyer \(pat@pat.net\)
bsh % s = "hello";
bsh % print\(s\);
hello
bsh % import \*;
Start ClassPath Mapping
Mapping: Archive:
file:/home/hclee/projects/GA/net.asgc.gap.core/lib/ext/bsh-2.0b4.jar
Mapping: Archive:
file:/home/opt/java/jdk1.5.0\_07/jre/lib/rt.jar
End ClassPath Mapping
bsh % print\(s\);
// Error: EvalError: Ambigous class names:
\[com.sun.org.apache.xpath.internal.operations.String,
java.lang.String\] : at Line: 35 : in file:
/bsh/commands/print.bsh : String .valueOf \( arg \)

Called from method: print : at Line: 4 : in file:
&lt;unknown file&gt; : print \( s \)
\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*

Could you please have a look? Thanks a lot\!

Best regards,
Hurng-Chun Lee

Reported by: *anonymous

Original Ticket: "beanshell/bugs/263":https://sourceforge.net/p/beanshell/bugs/263

**Comment by opeongo** [comment]
Ok, I can see how this could happen.  Import a class with a commonly used name like "String" and cause confusion in the interpreter.  

Take a look at part of what is in print.bsh for example
```java
void print( arg )
{
    if ( arg instanceof String
            || (arg instanceof Primitive && arg.getType() == Character.TYPE)
            || arg instanceof CharSequence )
        this.interpreter.println( String.valueOf(arg) );
    else
        this.interpreter.println( valueString(arg) + " :" + typeString(arg) );
}
```

If a new declaration for String comes along then of course the next time that this command is executed the String class referenced several times here will be ambiguous.  This seems to be exactly the expected behaviour for BeanShell, and the advice here should be "Well don't do that".

Perhaps the one 'guard' that we could put in place would be to fully qualify every class in all of the scripts in the commands folder.  For example, instead of just ```String``` it should be ```java.lang.String```.  That partially fix breakage like this, but I am sure that there are creative people who could find another way to break things.  An ugly and intrusive change for no guarantee.

I say this is how BeanShell works, and there is no bug here.

**Comment by nickl-** [comment]
Tx @opeongo 

**Closed: works as implemented**
