### ISSUE TITLE
clone is broken

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#421]
clone does not work, as can be seen in this example:

```java
// clone.bsh
public class A implements Cloneable {
    String name;
    void whoami() {
        System.out.println("I am " + this + " my name is " + name);
    }
}

A a = new A();
a.name = "a";
a.whoami();

A b = a.clone();
b.name = "b";
b.whoami();
// end of clone.bsh
```
The output is:
```java
% java -cp bsh.jar bsh.Interpreter clone.bsh
I am A@589e56 my name is a
I am A@589e56 my name is a
```
This is with 2.0b4 and JVM 1.5.

\- Godmar

Reported by: gback

Original Ticket: "beanshell/bugs/283":https://sourceforge.net/p/beanshell/bugs/283

**Comment by opeongo** [comment]
Test script

[clone.bsh.txt](https://github.com/beanshell/beanshell/files/2303286/clone.bsh.txt)

**Comment by opeongo** [comment]
There does appear to be a problem here, although perhaps not the original issue.  When sourced the test script yields the following output:

```text
I am A@2e4553 my name is a
// Error: Target Exception: Method Invocation this.interpreter.source : at Line: 14 : in file: /bsh/commands/source.bsh : this .interpreter .source ( filename , this .caller .namespace )

Called from method: source : at Line: 1 : in file: <unknown file> : source ( "clone.bsh" ) Caused by: bsh.EvalError: Sourced file: clone.bsh : Typed variable declaration : Error in method invocation: Method clone() not found in class'A' : at Line: 13 : in file: clone.bsh : a .clone ( )

bsh.ReflectError: Method clone() not found in class'A'
```

**Comment by nickl-** [comment]
From what I can tell, `this` gets cloned as well, while we have 2 unique objects the internals are the same (fault).

```java
--> $0 = class A :Class
bsh % a = new A();
--> $1 = A@7cf10a6f :A
bsh % b = a.clone();
--> $2 = A@6debcae2 :A
bsh % a.whoami();
I am A@7cf10a6f my name is null
--> void
bsh % b.whoami();
I am A@7cf10a6f my name is null
```

Note:
From the [clone implementation]() find the instructions that says: By convention, the returned object should be obtained by calling super.clone. If a class and all of its superclasses (except Object) obey this convention, it will be the case that `x.clone().getClass() == x.getClass()`. 

So the test class should look like this:

**Comment by nickl-** [comment]
parent #660

**Comment by nickl-** [comment]
Turned out to be quite a challenge.

Eventually managed to update This reference, only to find out that the actual This context is shared, and the namespace, and the methods, and, and, and. Ended up having to deep copy just about everything.

We can now produce two independent instances, as is expected, after a clone.

Also completed the implementation as per the scripted clone method from `This.invokeMethod` which will now produce an actual cloned instance and not just a copied This namespace, all without the need to implement Cloneable, when calling clone within This context. As the two use cases are reusing the same code, instead of duplicating the effort.
