### ISSUE TITLE
There is a bug, when implementing interfaces.

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#422]
```java
public class ClassGeneratorUtil implements Constants {
    boolean classContainsMethod(
    Class clas, String methodName, String [] paramTypes ) {
        for( int j=0; j<methodParamTypes.length; j++) {
            // The j can greaterthan paramTypes.lenth
            if ( ! paramTypes[j].equals( methodParamTypes[j] ) ) {
                found = false;
                break;
            }
        }
    }
}
```
yuu can check then parameters count first. if parameters count is not equal, no need to compare others.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/284":https://sourceforge.net/p/beanshell/bugs/284

**Comment by nickl-** [comment]
Uhm you forgot to say what the "bug when implementing interfaces"  actually is. =)

The code snippet also doesn't implement what you are referring to (checking parameter count) so if I have to guess then I give up.

Instead lets look at the current implementation of `ClassGeneratorUtil.classContainsMethod` and you will notice that we are now checking the parameter count too...

https://github.com/beanshell/beanshell/blob/678e6907c80d5880883648adabc3a759976aecb9/src/main/java/bsh/ClassGeneratorUtil.java#L767-L782


```
paramTypes.length == method.getParameterCount()
```

But as far as the "need to compare others" go, there is no point in comparing the parameter count if we don't have a method with the same name and since we are looking for exactly such a method (one with such a name) there is really no getting past comparing names.

From the current implementation I really can't see anything that needs improving and in the absence of any specific instruction from this issue I am only left with one conclusion...

**Closed: implemented**
