### ISSUE TITLE
==

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#445]
eval returns errors for boolean == operations

Reported by: *anonymous

Original Ticket: "beanshell/bugs/307":https://sourceforge.net/p/beanshell/bugs/307

**Comment by nickl-** [comment]
Trying to understand this issue is a parser error.

`boolean` is a reserved word, identifies a primitive type. If you are trying to use it as an identifier you will get a parser error.

Not sure what `operations` means to you but in this context `operations` is an undefined variable initialised with value `void`

**Closed: bogus**
