### ISSUE TITLE
automatic conversion x->int with 2^31<=x<2^32 doesn't work

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#455]
$ bsh
BeanShell 2.0b1.1 - by Pat Niemeyer \(pat@pat.net\)
bsh % int i = 0xff000000;
// Error: Parser Error: Parse error at line 1, column 9 : Error or number too big for integer type: 0xff000000
bsh % 

In Java this works \(assigned int value is -16777216 in this case\). Any yes, this is a feature, and it is used in real-world programs \(image manipulation for example\). Since Beanshell aims for 100% Java compatibility, it is a bug that this doesn't work in Beanshell, right?

Reported by: oklischat

Original Ticket: "beanshell/bugs/317":https://sourceforge.net/p/beanshell/bugs/317

**Comment by nickl-** [comment]
This should be strictJava, we are still in the process of testing all the strict java rules. Maybe for BeanShell 4.0???

```java
bsh % int i = 0xff000000;
// Error: Internal Error: cannot assign number 4278190080 to type int
bsh % this.interpreter.strictJava = true;
--> void
bsh % int i = 0xff000000;
--> $0 = -16777216I :int
bsh % this.interpreter.strictJava = false;
--> void
bsh % val = 0xff000000;
--> $1 = 4278190080L :long
```

**Comment by nickl-** [comment]
I wouldn't call it a feature, it's just what happens when the data size overflows it starts populating from the bottom again. You cannot know exactly what the value is and why java doesn't allow assigning down with an error like:

```java
jshell> long ll = 3;
ll ==> 3
jshell> int ii = ll;
|  Error:
|  incompatible types: possible lossy conversion from long to int
```

To see the problem lets multiply `Integer.MAX_VALUE` to see what happens.
```java
jshell> Integer.MAX_VALUE * 2
$346 ==> -2
jshell> Integer.MAX_VALUE * 3;
$347 ==> 2147483645
jshell> Integer.MAX_VALUE * 4;
$348 ==> -4
jshell> Integer.MAX_VALUE * 5;
$349 ==> 2147483643
jshell> Integer.MAX_VALUE * 6;
$350 ==> -6
```

As you can see it is not consistent and there is no way to tell what the actual value is.

Beanshell will automatically safely cast down for you within the type's available size;

```java
bsh % long ll = 3;
--> $8 = 3L :long
bsh % int ii = ll;
--> $9 = 3I :int
```

And will also grow automatically once available size has been reached. Lets look at what those actual values were supposed to be.

```java
bsh % Integer.MAX_VALUE *2;
--> $0 = 4294967294L :long
bsh % Integer.MAX_VALUE *3;
--> $1 = 6442450941L :long
bsh % Integer.MAX_VALUE *4;
--> $2 = 8589934588L :long
bsh % Integer.MAX_VALUE *5;
--> $3 = 10737418235L :long
bsh % Integer.MAX_VALUE *6;
--> $4 = 12884901882L :long
```

Lets see what happens if we use the `pow` operator, something not implemented in java but available in BeanShell.

```java
bsh % Integer.MAX_VALUE **2;
--> $0 = 4611686014132420608L :long
bsh % Integer.MAX_VALUE **3;
--> $1 = 9903520300447984150353281023W :BigInteger
bsh % Integer.MAX_VALUE **4;
--> $2 = 21267647892944572736998860269687930881W :BigInteger
```

Or if we take it from `Byte.MAX_VALUE` for a slower increment.

```java
bsh % Byte.MAX_VALUE **2;
--> $0 = 16129I :int
bsh % Byte.MAX_VALUE **3;
--> $1 = 2048383I :int
bsh % Byte.MAX_VALUE **4;
--> $2 = 260144641I :int
bsh % Byte.MAX_VALUE **5;
--> $3 = 33038369407L :long
bsh % Byte.MAX_VALUE **6;
--> $4 = 4195872914689L :long
bsh % Byte.MAX_VALUE **7;
--> $5 = 532875860165503L :long
bsh % Byte.MAX_VALUE **8;
--> $6 = 67675234241018880L :long
bsh % Byte.MAX_VALUE **9;
--> $7 = 8594754748609397760L :long
bsh % Byte.MAX_VALUE **10;
--> $8 = 1091533853073393531649W :BigInteger
bsh % Byte.MAX_VALUE **11;
--> $9 = 138624799340320978519423W :BigInteger
```

The idea is not to loose any data which cannot be guaranteed with the standard java implementation. `BigInteger` and `BigDecimal` have been granted full citizenship and can be treated the same as any primitive or wrapper type.
