### ISSUE TITLE
failure in run() command corrupts the interpreter

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#508]
It seems that when the object of the beanshell `run()` command fails some kind of corruption happens to the interpreter.

Here is an example of a script to be run, guaranteed to throw an exception (from fail_me.bsh):
```java fail_me.bsh
throw new Exception("boom");
```
Here is an invoking script that demonstrates the problem (from run_fail.bsh):
```java
try { run("fail_me.bsh"); } catch ( bsh.EvalError e ) { print("First run failed with EvalError"); } 

try { run("fail_me.bsh"); } catch ( Throwable fne ) { print("Second run failed with "+fne); }
```

If I start up an interpreter and source the invoking script 
`source("run_fail.bsh");`
and then follow up with an `exit()` command, the script will produce the following output:
```
C:\github\beanshell>java -cp target\classes bsh.Interpreter
BeanShell 2.1.0-SNAPSHOT - by Pat Niemeyer (pat@pat.net)
bsh % source("run_fail.bsh");
First run failed with EvalError
Second run failed with java.io.FileNotFoundException: C:\github\beanshell\null\fail_me.bsh (The system cannot find the path specified)
--> $0 = null :null
bsh % exit();
// Error: Evaluation Error: Undefined variable or class name while evaluating: b
sh.system.shutdownOnExit : at Line: 10 : in file: /bsh/commands/exit.bsh : bsh .
system .shutdownOnExit

Called from method: exit : at Line: 2 : in file: <unknown file> : exit ( )
bsh %
```

Notice the 'null' that is in the path name given in the exception.  Obviously not a problem during the first invocation.

[run_fail.bsh.txt](https://github.com/beanshell/beanshell/files/2307013/run_fail.bsh.txt)
[fail_me.bsh.txt](https://github.com/beanshell/beanshell/files/2307015/fail_me.bsh.txt)

**Comment by opeongo** [comment]
I had a look in to this a bit more.  It turns out that it has nothing to do with the exception being thrown.  Simply using the run command a second time in the interpreter causes the problem.  Working off the previous `run_fail.bsh` example, just changing the fail_me.bsh file to have:
```java
print("hello");
```
is enough to trigger the problem the second time the run command is invoked.

I tried to dig in to see what was going on and found that the problem showed up at commit de15ce30c79090d4c16478ec139cb41daa044a7d.  Before this commit multiple run commands worked correctly.

I am not sure what is happening here, but it looks like during the first invocation the `run()` object is prepared, and gets it's own namespace (named ''run') that has the `isMethod` property set.

During the second invocation the `run()` object is looked up in a namespace, and the method is bound to the `global/BlockNameSpace` namespace that does not have the `isMethod` property set.

Because of these differences to the `Namespace.isMethod()` property, `overrideChild` at Name:906 is set to false during the first invocation or `run()`, and in the second and subsequent invocations `overrideChild` is set to true.

There are a few things going on here that I don't fully understand with the overrideChild, so it willl require a bit more digging around to figure out.

**Comment by nickl-** [comment]
I also noticed something dodgy with the fail script but since it is meant to fail I didn't give it further attention. 

Thank you for the detailed investigation feedback... will look into this.

**Comment by opeongo** [comment]
The problem doesn't seem to have anything do with what is happening within the script that the ```run``` command executes.  A script that just contains a single return statement will show the problem.

The problem seems to be related to having the ```extend``` command (part of what happens within the ```run``` command) execute within a try block.  It seems that the try block will will set the ```overrideChild``` variable to true, and then the namespace at the top of the callstack gets swapped for a BlockNameSpace.  This causes confusion about the namespaces that the extend command is trying to set as the new parent and then prune.  Without the try block there is a namespace for the ```run``` method, and this is the one that gets pruned.  With the try block it is the BlockNameSpace that gets pruned and disconnected from it's parent.

Here is a simple sequence of commands to replicate the problem:

```
bsh % run("script_to_be_run.bsh");  // this works ok

bsh % try { run("script_to_be_run.bsh"); } catch (Exception ex) { ex.printStackTrace(); }  // works first time

bsh % try { run("script_to_be_run.bsh"); } catch (Exception ex) { ex.printStackTrace(); }  // fails second time
```
The failure that happens is a file not found error because the bsh.cwd variable no longer exists, and the Interpreter.pathToFile command (called by Interpreter.source) generates an invalid file name.  bsh.cwd is not found because the namespace got clobbered.

I cannot follow the logic for the overrideChild condition, but it seems like this is an important factor.

[script_to_be_run.bsh.txt](https://github.com/beanshell/beanshell/files/3933771/script_to_be_run.bsh.txt)

**Comment by nickl-** [comment]
Still need to make time to look into this.

**Comment by nickl-** [comment]
@opeongo 
So if I am correct, in order to make this fix 2 unit tests need to be scrubbed `override_child_namespace` and `override_child_child_namespace`?

That seems extreme, is there no other recourse? Only reading the code can't really comment unless having an environment for testing. Can we hold this one?

**Comment by opeongo** [comment]
Yes, we should look at this one some more.

But I think that the metric of 'removing 2 unit tests' is the wrong one to look at.  The de15ce3 commit that is being reverted broke other features, in particular using the `eval()` command irrevocably messes up the callstack and breaks the interpreter.  The de15ce3 commit may allow those two unit tests, but it breaks existing core functionality in the interpreter, so it has to be reverted and reworked anyway.  Can we agree on this?

I tried to follow through and figure out how to fix this problem but I got lost.  Instead I took a look at what the de15ce3 commit was trying to achieve.

When I looked at the unit tests it seems that the patch enables that that undeclared variables within methods should be looked up in the most local scope in which the scripted method was being run.  Ok, but I am not convinced that this is the natural and obvious way that the variables should be looked up.  In fact, this behaviour is not something that I would have expected or have chosen.  To me it would be more natural to think of the scripted methods as closures that capture the variables in the immediate context where the script is declared.  Having the runtime look up the variables in a different context really breaks encapsulation and makes it hard to reason about where the values are coming from.  An inadvertent duplicated variable name could screw up a script and be very difficult to track down.  

What about this code? This prints the number from the declaring context (1), not the number from the runtime context (2).  This is the Java way so is this more natural and less surprising?
```java
public class A {
  int v = 1;
  Runnable r() {
    return new Runnable() {
      public run() {
        System.out.println(v);
      }
    }
  }
  static class B {
    int v = 2;
    void apply(Runnable r) {
      r.run();
    }
  }
  public static void main (String[] args) {
    new B().apply(new A().r());
  }
}
``` 

So to look up undeclared variables in the local context or the declared context is a design choice and is subjective.  And it looks like the old bsh-2.0b5 did not do this (it appears to me that it looks up undeclared variables in the declaring context).  So which design is better by the metric of more natural and obvious?  Is the change that de15ce3 makes really desirable?  I would say the old behaviour is more preferable because it acts more like a closure and like how Java works, so it is a more familiar pattern.  To me the new behaviour is different goes against the principle of least surprise. 

So de15ce3 needs to be reverted.  The question is does the functionality it contains need to be re-engineered and reapplied?

**Comment by nickl-** [comment]
> Yes, we should look at this one some more.

Need to come back to this. Remind me if I forget.

**Comment by opeongo** [comment]
Ok I restored the unit test, but with the results as would be expected in Bsh2.0.

This commit still needs to be reverted.  It causes unrecoverable interpreter corruption after the eval() function is executed.

**Comment by nickl-** [comment]
> Ok I restored the unit test, but with the results as would be expected in Bsh2.0.

Ahh thank you very much, that now makes things much clearer and better than removing the tests. I keep forgetting you are trying to roll back, while all I see is code removed, changed, and new code added. When it is actually old garbage being put back.

None the less...

### I have to disagree:

> This commit still needs to be reverted. It causes unrecoverable interpreter corruption after the eval() function is executed.

Sure the change caused unforeseen effects elsewhere, these things happen and why code coverage is so important. And sure if you roll it back those problems are not there anymore, but the problems the commit fixes then returns. Why don't we just fix the unforeseen, why is a roll back the only option?...or even desirable.

### Identify the problem:

Unless I am mistaken we have only 2 methods, currently raised here in discussion, which are acting out, being `run()` and `eval()`. As fate would have it, these 2 are also no ordinary methods, so it begs to reason that they may be exceptions to the rule (of common methods) and may very well require special attention.

### eval is not a method

Looking at the command's main description:
https://github.com/beanshell/beanshell/blob/680765207eca5c190d55009cc1f4a589365070eb/src/main/resources/bsh/commands/eval.bsh#L6-L7

Unless it is overly simplified...eval should act the same whether it was there or not. 

In other words:

```java
foo = 1;
eval('bar = foo;'); // should behave the same as bar = foo; without the eval
baz = bar; // baz should be 1
```

So what would happen if we were able to say `eval.isMethod = false`? Would that resolve the problems without any further hassles?

### run does not inherit (or does it?)

Again looking at the description everything becomes clear:
https://github.com/beanshell/beanshell/blob/680765207eca5c190d55009cc1f4a589365070eb/src/main/resources/bsh/commands/run.bsh#L2-L4

So run ignores the current namespace hierarchy and extends from global or the top most namespace. Similar to eval but will it be enough to just treat `run.isMethod = false;` so it does not attempt to look for children overrides. Surely everything that is declared in its own namespace should not trickle back to global as is expected from a sandbox.

### other methods to investigate

Some other "special" methods which may need some TLC as well, are `source()`, `extend()`, and `exec()` which makes but a handful of concerns... unless you can think of more.

### root cause

The dreadful commit de15ce3 sets out to solve a simple problem, am I a method/block, and am I a parent, and does a child overwrite a value which invalidates my context. Similar to problem solving, finding a change which caused something unexpected to happen elsewhere, if removed it appears resolved, but is this the root cause or is there something else which has only become apparent now. 

As we can see, in fact something completely different is messed up that needs attention. It has always been there by design and while it appeared to work as expected it was not quite complete. Only now we get to see the problem and are given the chance to discover, fix, improve, solidify, and complete.

**Comment by nickl-** [comment]
TODO: We need failing unit tests for the scenarios raised above.

**Comment by nickl-** [comment]
> This bug has nothing to do with inheritance, and this reversion will not change your example from working. The change that this will revert was looking up and using variables in the namespace where the scripted method was being executed in, rather than using the variables from the namespace that the function was declared in. This behaviour causes the namespace stack to become irrecoverably corrupted and subsequently run scripts to fail so it is a serious bug.

Instead of reverting fix the bug.

**Comment by nickl-** [comment]
Found the proper fix which ended up having nothing to do with the commit reverted fix.

Ends up methods loose their `isMethod` flag when overriding the local namespace. This may very well be an issue in many more scenarios than the `eval` and `run` examples identified and added to the unit tests.
