### ISSUE TITLE
Error in dynamic evaluation

### ISSUE THREAD

**Issue by sergioszy** [beanshell/beanshell#513]
Hello,
with the current version 2.1.0-snapshot, is evaluating the Object[] creation just one time.

This is the example:
```java
import bsh.EvalError;
import bsh.Interpreter;

public class TestBSH {
	public static void main(String[] args) throws EvalError {
		Interpreter bsh = new Interpreter();
		String toeval = null;
		toeval = "import java.util.ArrayList;  testList() {   ArrayList xxx = new ArrayList(); ";
		toeval = toeval + "int c0=0; for ( c1=0; c1 < 10; c1++ ) { xxx.add( new Object[] { \"XX\" + c0,  c0 + \"YY\"  } ); c0++;  }";
		toeval = toeval + "for ( c1= 0; c1 < 10; c1++ ) { print( xxx.get(c1)[0] ); } }";
		bsh.eval(toeval);
		bsh.eval("testList();");
	}
}
```
With bsh-2.1.0-snapshot produces 
```
XX0
XX0
XX0
XX0
XX0
XX0
XX0
XX0
XX0
XX0
```

With bsh-20b4 produces
```
XX0
XX1
XX2
XX3
XX4
XX5
XX6
XX7
XX8
XX9
```

Best regards

**Comment by opeongo** [comment]
This bug has to do with array initializer caching and seems to have been introduced in d20de2f5084a6a4c3e0c5941447e0663e49c660c.

**Comment by nickl-** [comment]
This caching was introduced because of type inference, since we have to evaluate the initialisers to deduce the type, caching the result avoids the need to evaluate duplicate the process.

**Comment by nickl-** [comment]
@sergioszy Thank you for your patience!

Fixed the caching issue and also added empty list initialisation support.

**Some notes:**

You do not have to import `java.util.ArrayList` because the `java.util` package is imported by default. 
See `Namespace` for the list of default imports at `loadDefaultImports()`.

https://github.com/beanshell/beanshell/blob/9b544dd9e4f9e524c14bf726eebb525be773d3b8/src/main/java/bsh/NameSpace.java#L1239-L1258

Instead of:
```java
ArrayList xxx = new ArrayList();
```
You can now use one of the following 3 different options to produce the same.
```java
List xxx = {};
xxx = new List {};
xxx = (List) {};
```

Of course the following will also work.
```java
ArrayList xxx = {};
```

More on this at [Arrays 3.0 with Collections](/beanshell/beanshell/issues/89) if you are interested, you can also catch up with other enhancements and share your comments by following the [discussion labeled](/beanshell/beanshell/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion) issues.

**Comment by sergioszy** [comment]
Hi,
There is still some problem, I will attach an example.
The problem seems to be when a new Bean is referenced in the new Object [].

		Interpreter interpreter2 = new Interpreter();
		try {
			List lista = new ArrayList<>();
			lista.add("ONE");
			lista.add("TWO");
			lista.add("THREE");
			lista.add("FOUR");
			lista.add("FIVE");
			
			interpreter2.set("LISTA", lista );
			
			String expre = "int c0=0; while ( c0 < lista.size() ) {"
					+ " System.out.println( lista.get(c0) ); c0++; }";
			
			interpreter2.set("lista", lista);
			interpreter2.eval(expre);
/*
this is Ok and shows.
ONE
TWO
THREE
FOUR
FIVE
*/			


		    lista = new ArrayList<>();
			
			Prueba pru1 = new Prueba();
			pru1.attr1 ="ONE";
			lista.add( pru1 );
			pru1 = new Prueba();
			pru1.attr1 ="TWO";
			lista.add( pru1 );
			pru1 = new Prueba();
			pru1.attr1 ="THREE";
			lista.add( pru1 );
			pru1 = new Prueba();
			pru1.attr1 ="FOUR";
			lista.add( pru1 );
			pru1 = new Prueba();
			pru1.attr1 ="FIVE";
			lista.add( pru1 );
			
			expre = "import nt.comun.test.Prueba; c0=0; List nlist2 = new ArrayList(); while ( c0 < lista.size() ) {"
					+ " nlist2.add( new Object[] { lista.get(c0).attr1 } ); c0++; }"
					+ " c0=0; while ( c0 < nlist2.size() ) {"
					+ " System.out.println( nlist2.get(c0)[0]  ); c0++; }";
			
			interpreter2.set("lista", lista);
			interpreter2.eval(expre);
		}
		catch (EvalError e1) {
			e1.printStackTrace();
		}
/*
this must shows the same that first example but shows
ONE
ONE
ONE
ONE
ONE
*/


package nt.comun.test;

public class Prueba {
	public String attr1;
	public String attr2;
	public String producto_c;
	public Number canped_d;
}

**Comment by nickl-** [comment]
@sergioszy Yip! Well spotted!

That was the one last scenario which you caught there, the one that doesn't need any caching...go figure.

Very good thing that you found it now with everything still fresh in mind. After going over everything again with a fine toothed comb I finally realised the proper fix nay, the solution. Instead of what still felt, very uneasily till now, like a patch to the problem instead of a fix. 

Managed a few other optimisation tweaks with some code clean ups and I believe this one is done and done. 

If I'm wrong you know what to do...
