### ISSUE TITLE
Compiled BeanShell ignores function definitions

### ISSUE THREAD

**Issue by davidekholm** [beanshell/beanshell#528]
BeanShell reports to implement Compileable, still, compiled code can't refer to earlier function declarations, no matter if they were simply evaluated or compiled, then evaluated.

Pseudocode:
be = new BshScriptEngine();
func = be.compile("int square(int x) { return x*x; }");
func.eval();
be.eval("square(5);") ; // Fails. Function not found
c2 = be.compile("square(5);")
c2.eval(); // Fails too. Function not found

**Comment by nickl-** [comment]
Need to investigate.

**Comment by nickl-** [comment]
`bsh.engine.BshScriptEngine` compile uses  `bsh.PreparsedScript` to wrap the source and invoke it.

https://github.com/beanshell/beanshell/blob/04ae91a212e96c8a39cd4dc82bb52c2df4773cdf/src/main/java/bsh/engine/BshScriptEngine.java#L179-L200

`bsh.PreparsedScript` sandboxes the "compiled source" inside a method called `_execute`.

https://github.com/beanshell/beanshell/blob/04ae91a212e96c8a39cd4dc82bb52c2df4773cdf/src/main/java/bsh/PreparsedScript.java#L28-L29

`bsh.PreparsedScript` invoke takes a map of namespace variables which are set before the sandboxed source method is invoked which for the `javax.script.CompiledScript` means passing a `javax.script.ScriptContext`.

https://github.com/beanshell/beanshell/blob/04ae91a212e96c8a39cd4dc82bb52c2df4773cdf/src/main/java/bsh/PreparsedScript.java#L57-L65

A working example of a compiled square function passing `x`:

```java
        ScriptEngine engine = new ScriptEngineManager().getEngineByName( "beanshell" );
        CompiledScript square = ((Compilable) engine).compile("return x*x;");
        ScriptContext ctx = engine.getContext();
        ctx.setAttribute("x", 5, ENGINE_SCOPE);
        assertEquals(25, square.eval(ctx));
```

Not sure if this was the intended implementation of `javax.script.Compilable` but this is how it is implemented in `bsh.engine.BshScriptEngine`. Because the "compiled source" is sandboxed inside of a method block no methods or variables will be directly exported. You could possibly manually register methods with the namespace but the `bsh.PreparsedScript` runs in a separate interpreter instance and namespace from the rest of the scripting engine which may make this redundant.

The `javax.script.CompiledScript` returned from compile also does not support eval of any source for execution and only exposes methods for passing bindings so it would appear this was the intended use case.

**Closed: added unit test example**

**Comment by nickl-** [comment]
Here is another approach which does expose the method:

```java
        ScriptEngine engine = new ScriptEngineManager().getEngineByName( "beanshell" );
        CompiledScript script = ((Compilable) engine).compile("square(x) { return x*x; } return this;");
        engine.getContext().setAttribute("script", script.eval(), ENGINE_SCOPE);
        assertEquals(16, engine.eval("script.square(4);"));
        assertEquals(25, engine.eval("script.square(5);"));
```

Then you can even take it another step further:

```java
        engine.eval("square(x) { return script.square(x); }");
        assertEquals(16, engine.eval("square(4);"));
        assertEquals(25, engine.eval("square(5);"));
```

**Comment by davidekholm** [comment]
Thanks for returning to this Nick (even if it's been a long time). I guess my key objection is that your solutions would require the skin developer's code to be adjusted to work with compiled BeanShell. I'd naturally prefer if compiled BeanShell didn't require a different API/syntax to work. As long as the work is on me (jAlbum's developer) and not the skin developer, it's fine.

**Comment by nickl-** [comment]
@davidekholm 
> Thanks for returning to this Nick (even if it's been a long time).

Don't we all wish for more time. Thank you for your patience.

>  I guess my key objection is that your solutions would require the skin developer's code to be adjusted to work with compiled BeanShell.

Please keep in mind that we don't know jAlbum or should we focus on any one use case or implementation that uses BeanShell, it should work for all current and yet unimagined purposes. I cannot help you with any specific issues you have with jAlbum because I don't know anything about the implementation.

> I'd naturally prefer if compiled BeanShell didn't require a different API/syntax to work. As long as the work is on me (jAlbum's developer) and not the skin developer, it's fine.

When you are talking about **"compiled BeanShell"**, you are not referring to BeanShell at all but instead you are using the Java Scripting API as defined by the [JSR-223 Specification](https://jcp.org/aboutJava/communityprocess/final/jsr223/index.html). BeanShell has implemented the API through the class `bsh.engine.BshScriptEngine`, for your convenience, but the interfaces you are using are all from the `javax.script` package and that is maintained by Oracle. We cannot do anything to help you with that either.

What I've tried to do best I can was to give you an example of how to expose the method `square` defined in a compiled script to another script engine. Because each compiled script is associated with it's own script engine.

From JSR-223 specification:
> Each CompiledScript is associated with a ScriptEngine -- A call to an eval method of the CompiledScript causes the execution of the script by the ScriptEngine. Changes in the state of the ScriptEngine caused by execution of tne CompiledScript may visible during subsequent executions of scripts by the engine.

Compiled scripts and interpreted scripts are not interchangeable they serve separate purposes. Think of compiled scripts as a command or application that gets executed repeatedly. You can change the arguments/parameters and you can use what it returns. But you cannot make changes to the script or add additional functionality.

For interpreted scripts it allows you to continue adding more lines of code to the script, making changes to the functionality and continue execution. All previous code snippets, like function definitions, are exposed to new code snippets that gets added later. This works more like a terminal shell or console application that continues to change functionality on the fly instead of having one single precompiled purpose. I hope this makes more sense...

You also don't have to use the Java Scripting API at all you can use the BeanShell Interpreter directly in your code. Which will be much more flexible than working within the confines of the Java Scripting API.

```java
Interpreter bsh = new Interpreter();
bsh.eval("print('Hello World');");
```

How you choose to use BeanShell is up to you just like choosing the separation of concerns, between designers and coders, in your application is also entirely up to you. I personally don't think compiled scripts is what you are after but that is just my hunch, whatever works for you makes us happy.

Good luck!

**Comment by davidekholm** [comment]
I have the feeling we're talking across each other Nick :-(. First, We rely on JSR-223 to be able to offer multiple scripting languages to jAlbum skin developers, second, the original BeanShell developer was instrumental to the JSR-223 specification. If he made significantly worse design choices for it than for it's predecessor, that's sad. Third, I SIMPLY wish interpreted BeanShell vs compiled BeanShell to behave similarly to interpreted and compiled JavaScript in JSR-223. I.e. you gain performance by doing the textual parsing phase once for scriptlets that are executed multiple times. Forth: Does the text "Each CompiledScript is associated with a ScriptEngine" imply that each compiled script should have its own UNIQUE script engine? That's not the way it works in JavaScript in JSR-223.
