### ISSUE TITLE
Maven does not build on windows.

### ISSUE THREAD

**Issue by orbitalair** [beanshell/beanshell#532]
The Maven tool won't build beanshell under windows out of the box.

Tonite I installed the latest Git, Maven and gave it a go in Windows7 64bit.

Prob 1:  If you setup Git to NOT CHANGE line endings, maven compiles ok, but the style checker will fail on every single file. Its looking for os line endings?

Prob 2: If you DO change the line endings to windows CRLF, then the strings.bsh test will fail.  Because the test is looking for specific hardcoded line endings in embedded strings for test purposes.

One is able to get a jar file to build by disabling the maven tests. mvn install -Dmaven.test.skip=true

This is my first time using maven so I don't have a fix yet.  I looked to see what IF tests are done based on OS type and there was not a clear answer.   I would set it such that if the host is windows, change all the line endings, and fix up the strings.bsh test file.  I dont have a dump because I hacked on strings.bsh for a while and was no longer out of the box.

orbitalair

**Comment by orbitalair** [comment]
After trying on 2 other machines in windows, on cmd line maven and in netbeans, everything seems ok except the checkstyle test.  IF the authors feel that the git files have a trailing CRLF, then theres something up with GIT because it stripped a bunch of files for me.  I'd suggest adding the checkstyle to the POM and disabling it, or fix the files so this test passes.

orbitalair.

**Comment by nickl-** [comment]
Interesting, thank you for pointing this out @orbitalair 

I have only tested cloning with git and building on Windows which didn't pose any of these issues.

Are you using the development branch merge-fork-beanshell2 or does this happen on master?

There should not be any CRLF files on the default branch and all tests pass so you should not need to skip tests.

**Comment by orbitalair** [comment]
I checked and it seems I have the merge-fork-beanshell2 selected.
Oh, and all the tests work, except the checkstyle which is looking for a blank line at the end of the code files.  I modified my POM to have a checkstyle section proper where I disabled the check for myself, tho changing the checkstyle config would also work.

I will try the master in the next couple of days to see what it does.

**Comment by nickl-** [comment]
We actually have script `scripts/bsh-code-style-fixup` it requires `bash` though so it won't work on `windows`, maybe with `cygwin` perhaps.

It should take care of all the whitespace issues like tabs to spaces, dos to unix, trailing spaces and  new line at end of file nonsense.

Strange...

**Comment by nickl-** [comment]
Tested on windows.
Had no problem with `checkstyle` or git wanting to convert line endings so this is not something standard or out of the box so to speak. Perhaps you changed something to git standard configuration?
 
There was however an issue on windows with one of the unit tests `strings.bsh`.  We found an anomaly with the parser and strings where you can escape the end of line and create a multi line string.

```
str = "\
line 1\
line 2\
line 3\
";
```
This happens because the parser turns the "\n" into "\\\\n" which then gets turned into "\n" again anyway the problem on windows is that line endings are two characters "\r\n" so only the carriage return gets escaped "\\\\r\n" and we loose the "\n" which really confuses everything. Since this was merely an oddity and hardly a language feature I removed it from the tests. Maven now completes with `BUILD SUCCESS`. Yeah!

This is the command sequence I used in Command Prompt:

```
git clone https://github.com/beanshell/beanshell.git
cd beanshell
mvn install
```

These are the version numbers which might make a difference.

Windows 10 Pro
git version 2.16.1.windows.4
Apache Maven 3.5.4 

**Closed: Issue resolved**
