### ISSUE TITLE
Regression "Typed variable declaration error" introduced by 2.0b6

### ISSUE THREAD

**Issue by pmouawad** [beanshell/beanshell#533]
Hello,
At Apache JMeter we got the following bug report:

- https://bz.apache.org/bugzilla/show_bug.cgi?id=63065

The problem is the non-declaration of untyped variables inside block scope:

import java.util.HashMap;
HashMap vars = new HashMap();;
if (true) {
 // Here var1 is not typed and in a block
  var1 = "some value";
}
vars.put("var", var1);

will reproduce the behaviour.

If you replace the bsh-2.0b6.jar file by bsh-2.0b5.jar, the issue disappears.

Since we cannot revert version to 2.0b5 due to security issue, is there a chance to have a release with a bugfix for it ?

Thank you

**Comment by pmouawad** [comment]
Thanks and kudos to you @nickl- 

Unfortunately, I am also working on other OSS projects, and my time is limited :-)

For now, we'll document the issue , and anyway I wouldn't write code in this ugly way.

**Comment by nickl-** [comment]
Did you have a look at the [roadmap](/beanshell/beanshell#development-road-map)? It also lists all the items we have completed.

> Unfortunately, I am also working on other OSS projects, and my time is limited :-)

IKR... it would really help us if you would use the development branch so that it gets more exposure. I will try and address any issues you do experience as a priority in return.

> For now, we'll document the issue , and anyway I wouldn't write code in this ugly way.

From looking at the code example the result is as expected, `var1` is scoped within the block and hence not visible from outside the block, something that was not working correctly in past releases. As we attempt to let java take the lead on these matters I would have to say: **works as expected, issue closed**

**Comment by pmouawad** [comment]
If you make dev branch available within a nightly build, maybe we can discuss this .

But if we need to build it, then it means another complexity in our build process.

Thanks
