### ISSUE TITLE
Add safe navigation ?. and null coalescing ?? operators

### ISSUE THREAD

**Issue by drosenbauer** [beanshell/beanshell#536]
I propose that Beanshell implement a [safe navigation operator](https://en.wikipedia.org/wiki/Safe_navigation_operator), like many other languages. This would be a deviation from Java syntax, but Beanshell already has enough of those that this shouldn't be a serious argument against it. 

Specifically, the operator `?.` would behave as `.` if the LHS is not null. Otherwise, the entire expression would return null. If we're really going all-out, copying C#'s safe array dereference `a?[0]` syntax and CoffeeScript's `a?()` would also be neat.

We'd need to discuss how to handle chaining. Groovy attempts to invoke each item in the chain `a?.b()?.c()?.d()`, even if `a` is null. That means that if a `?.` is accidentally missed (easy to do), a NPE is thrown. I feel this is not intuitive and that the lookup and invocation of `c` should never even be attempted after the first `?.` check has a null LHS.

**Comment by nickl-** [comment]
> This would be a deviation from Java syntax, but Beanshell already has enough of those that this shouldn't be a serious argument against it.

Oi! We are are `strictJava` all the way!! =)

I'm sure you don't know the least of it. Have you looked through the [discussions](/beanshell/beanshell/labels/discussion) specifically at Arrays 3.0 #89 

I like the idea a lot but lets keep it on the back burner for now there are other priorities... do I hear someone say: lambda support yes please.

We need to be a little careful with bells and whistles though. Let me put it this way, first and foremost beanshell is a Java interpreter. This is not our only goal though, making beanshell a kickass scripting language is a close second. Something which has already caused some waves in the community and lead to me writing the BeanShell vs Java #501 post.

I also know there exists an anti groovy sentiment who think it's too radical. But that doesn't matter we don't need another groovy anyway and the way I see it if you don't use a feature then it shouldn't have to bother you. Finding a middle ground is what put me on the natural evolution of BeanShell mantra, the closer we stay to Java to smoother everything goes. Just something to keep in the back of your mind as I suspect we're going to get more of these requests from you. =)

> I feel this is not intuitive and that the lookup and invocation of c should never even be attempted after the first ?. check has a null LHS.

I agree with you, it doesn't compute otherwise... what's the point then. I just got a brainwave, what if you implement it without the need of an operator. Default behaviour is no NPE. Hmmmmmm pondering..... what are the caveats?

**Comment by nickl-** [comment]
Java is also still missing null coalescing `??` which is fairly easy to implement.

No more:

```java
if (obj != null) {
   // do something
}
```

**Comment by nickl-** [comment]
Added 5 new operators ??, ??=, ?:, ?., and <=> see:

https://github.com/beanshell/beanshell/blob/67a7c655c16e222d8d0a1a16eddb7d075c5f8fa6/src/test/resources/test-scripts/operators.bsh#L54-L189
