### ISSUE TITLE
ASM upgrade to ver 7.0

### ISSUE THREAD

**Issue by jdinesh86** [beanshell/beanshell#557]
Any plan to release JDK 11 compatible version?

The latest version uses ASM6.2 and for Java 11 ASM7.0 is required.

**Comment by nickl-** [comment]
@jdinesh86 
> The latest version uses ASM6.2 and for Java 11 ASM7.0 is required.

Do you know if ASM7.0 is backward compatible with Java 8? We can currently compile with Java 8 and 9,  are there any other issues compiling with Java 10 and 11?

**Comment by jdinesh86** [comment]
@nickl- 
I am able to compile with openJdk11 and the tests are passing.

Here is the release notes of ASM where 7 supports java 11. 

https://asm.ow2.io/versions.html
https://www.reddit.com/r/java/comments/9se1z4/asm_70_released_official_support_for_java_11/

Java 11 forward incompatible features require ASM 7.0. See http://groovy.329449.n5.nabble.com/Support-of-Java-11-using-ASM-6-2-1-and-ASM-7-td5753586.html

I don't see anywhere that ASM 7 is not backward compatible. While the community is gearing up support for Java 11, I think it is key to be backward compatible at least down to java 8 to enable transition. I believe ASM 7 should have done the same.

**Comment by nickl-** [comment]
From what I can gather it refers to the class visitor API in other words ASM functionality for reading byte code of classes compiled with Java 11. 

> Even if NestMates are declared as class attributes, we have decided in ASM to not ignore them if there are present in the bytecode (a class compiled with javac 11) because this change for the VM is far from innocuous, if you scrap those attributes, you get IllegalAccessError laters, so if you use a ClassVisitor configured with the ASM6 API and ASM see a nestmate related attributes (NestHost or NestMembers) it will fail with an UnsuportedOperationException. 

BeanShell does not use this functionality we only generate classes using ASM. We only need ASM to produce new classes (scripted classes) we do not require existing classes to be modifiable. Some of the unused functionality even gets removed from the ASM source included with BeanShell to reduce size. I mention this because it is not a simple copy paste to upgrade ASM for BeanShell, some source blacks need to be commented out.

Java 11 and newer, should for the foreseeable future still be able to use classes compiled with Java 8 which is what ASM pre 7 will produce/generate so we should not have any immediate concerns. This is also why there are no build issues and why all the tests succeed compiling against Java 11.

Unless I am mistaken in this assessment we **do not** require ASM7.0 for now, at least not for BeanShell 3.0 release. We can look at upgrading ASM once the current road map is complete.

Marked out scope for BeanShell 3.0.

**Comment by jdinesh86** [comment]
@nickl- Thanks for the detailed explanation!

**Comment by nickl-** [comment]
Closed in favour of #656
