### ISSUE TITLE
Building from master is brittle with respect to newlines in source

### ISSUE THREAD

**Issue by harvv** [beanshell/beanshell#558]
(This is a minor issue with an easy workaround, but worth noting)

If the Java source files have non-platform-expected newlines (i.e. newline style differences between Unix and Windows), the prescribed build command of "mvn install" will die with errors from Checkstyle...(excerpt below):
[INFO] There are 199 errors reported by Checkstyle 8.18 with sun_checks.xml ruleset.
[ERROR] src\main\java\bsh\BlockNameSpace.java:[1] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src\main\java\bsh\BSHAllocationExpression.java:[1] (misc) NewlineAtEndOfFile: File does not end with a newline.
....(etc)....

This can most easily be triggered by using the "Download as ZIP" feature of Github rather than using the usual "git clone....".  However, this isn't the only way to trigger it.

NOTE: This is not an effort to open up a "code style strictness" debate.  It's simply a report that the build process is pretty brittle to something that's not an uncommon thing to happen.

**Comment by nickl-** [comment]
This issue was raised before #532 but it was found that the default scenarios should not cause line endings to change and that `CheckStyle` correctly checks for the undesired endings.

Keep in mind that `CheckStyle` is used to ensure code conforms for BeanShel project acceptability, any code submitted (by PR) for inclusion in BeanShell. If your projects uses different style applications then you are free to modify `CheckStyle` for your use or exclude it from the build process.

```
mvn install -Dcheckstyle.skip=true
```

**Closed: Works as implemented**
