### ISSUE TITLE
when I execute the eval method to parse the expression, a StackOverflowError occurs

### ISSUE THREAD

**Issue by pecdew** [beanshell/beanshell#560]
Hello, when I execute the eval method to parse the expression, a StackOverflowError occurs. 
My execution code is as follows:
```
        Interpreter interpreter = new Interpreter();
        StringBuilder statementBuilder = new StringBuilder("false || (");
        for (int i = 0; i < 500; i++) {
            statementBuilder.append(" false || ");
        }
        statementBuilder.append("true)");
        String statement = statementBuilder.toString();
        Object result = interpreter.eval(statement);
        System.out.println(result);
```
The error is as follows:
```
Exception in thread "main" java.lang.StackOverflowError
	... 
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:46)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
	at bsh.BSHBinaryExpression.eval(BSHBinaryExpression.java:117)
	at bsh.Interpreter.eval(Interpreter.java:659)
	at bsh.Interpreter.eval(Interpreter.java:750)
	at bsh.Interpreter.eval(Interpreter.java:739)
```
Stack memory overflow due to long expressions causing parsing, How to solve this problem?Can you optimize the algorithm under parsing?

**Comment by pecdew** [comment]
My vm parameter：-Xss160k

**Comment by nickl-** [comment]
When I execute that statement I get: (no closing `)`)

```
// Error: Parser Error: Unable to parse code syntax. Encountered: ; at line 2, column 1
```

It might help to consider the 160K stack size restriction if we start with a valid statement.

What exactly are you trying to test for, I fail to see how 500 binary expressions in a row is useful. Besides we need to know what exactly to optimise and in this example we must look at optimising repetitive binary expressions is this what you actually need?

If this is what you need that is fine I just want to make sure we are on the same page. Each type of language node has it's own complexities and hence memory requirement so it will all depend on what the script does and less about the actual length/size of the script.

**Comment by nickl-** [comment]
Some more thoughts:

In your example we are also looking at a single line statement. It may be far more memory efficient if this example used 500 separate if statements where each statement can be finalised and then garbage collected whereas a single line statement requires all allocations to remain active until it completes.

It is also not about the length of the line statement again, for example: Assigning a string value that is 5000 characters long will require less memory than your ±5000 character statement. In comparison.

Again it all depends on what exactly you are trying to prove.

**Comment by morris821028** [comment]
Hi, @nickl- . I suspect this problem is the leftist of this long expression, which generated by javaCC. If we want to have short circuit logic and performance, it should be a rightist syntax tree to avoid traverse whole syntax tree of this expression. So, we may need to adjust the java.jj syntax to gain rightist tree, not leftist one.

If stack overflow issue happened again, we could change evaluation implementation. Let it archive tail call optimization to reduce stack size, or use another solution to maintain stack.

**Comment by nickl-** [comment]
@morris821028 Oi! Who are you calling a leftist? =) *  kidding  *

I see what you are saying Ideally we only want the last token on the far right because it is the `true`. But how do we know it is at the end and not somewhere in the middle? 

Although JavaCC understands how to parse the grammar, it has no idea what it means. Sure true and false are the simplest forms of a boolean expression but they can be many other things too there is not much sense to make of what it is without context.

The problem is still the fact that this is a single line which needs to produce a value so everything remains referenced and can't be freed up.

I am sure if we were looking at more concise statements you would get a lot closer to the `true`.

Take your example:

```java
        Interpreter interpreter = new Interpreter();
        StringBuilder statementBuilder = new StringBuilder("x = false;");
        for (int i = 0; i < 500; i++) {
            statementBuilder.append("x |= false;");
        }
        statementBuilder.append("x |= true;");
        String statement = statementBuilder.toString();
        Object result = interpreter.eval(statement);
        System.out.println(result); // will contain the value of x = true
```

In this way we only ever need to consider three tokens, the `AmbiguousName` x, a binary assignment operator `|=` and the `PrimaryExpression` which is all we need to complete the statement, produce a result and move down to the next line (even though it's all still technically on the same line but never mind that). At least this leaves us with some wiggle room to even consider optimisation.

With the single line problem, for which there is no purpose to consider that it might be too long before the start, has no indication or modus to make it stop. Once down the rabbit hole the only way out is through unless the stack explodes before we make it. But that never happens we always make it to the other side. No worries mate!!! Even now that you have clearly proven it does go wrong and started all these discussions to find a solution so it never ever happens again... all I can come up with is: **Lets blame it on the rabbit!**

With separate statements it might not even be a problem. \o/ If it is a problem then we can take some sanity checks, have a break, run some diagnostics and even declare a mandatory vacation. It will all be fine because we can leave a bookmark and continue again later where we left off.

So take some smaller statements, have a good nights tests and come see me in the morning... Don't you worry, it will all feel much better soon.

**Comment by pecdew** [comment]
Hi @nickl- , thank you for your reply,

The situation is this, I have 500 conditional rules, the value of each conditional rule is true or false, and the relationship between these values is OR or AND, for example: true && ( false || false ||... (Omitted) || true )

Now, I just want to get the final result of the combination of these rule values, so I used Interpreter.eval() to get it. 

However, during the execution process, StackOverflowError was thrown. I guess it may be due to the expression being too long. But I don't know how to solve this problem, so come to ask for advice.

**Comment by nickl-** [comment]
@pecdew what I was trying to explain to you is that instead of using the comparison operators for OR `||` and AND `&&` all in one line rather use the assignment operators for or `|=` and AND `&=` in separate statements.


#### comparison operator BOOL OR `||`  or the assignment operator OR ASSIGN `|=`

```java
result = false || false || false || true || false; // times 500 in one line statement
result == true;

result = false;
result |= false; // result = result | false;
result |= false; // result = result | false;
result |= true;  // result = result | true;
result |= false; // result = result | false;
// times 500 single line statements.
result == true;
```

#### comparison operator BOOL AND `&&`  or the assignment operator AND ASSIGN `&=`

```java
result = true && true && false && true && false; // times 500 in one line statement
result == false;

result = true;
result &= true;  // result = result & true;
result &= false; // result = result & false;
result &= true;  // result = result & true;
result &= false; // result = result & false;
// times 500 single line statements.
result == false;
```

 - Every example tries to find the value for `result`. 
 - The single line statements uses the same data as the one line statement.
 - All the single line statements when complete will get the same value for result as the one line statement will.
 - All the single line statements together will not use as much resources as the one line statement.
- Change `||` for `|=` and change `&&` for `&=`.

Hope this makes more sense?

**Comment by morris821028** [comment]
@nickl- 

I think his problem maybe like these

```java
result = func(0) || func(1) || func(2) || ... || func(1024);
```

So, by your adjustment.

```java
result = false;
if (!result)  result = func(0);
if (!result)  result = func(1);
if (!result)  result = func(2);
...
if (!result)  result = func(1024);
```

We could do that if it started from writing script manually. However, if need to synchronize the source code, it needs to modify the original source code. Unfortunately, in most situation, they are external or no permission.

**Comment by morris821028** [comment]
@nickl- About javaCC compiler.

It could build the syntax tree, like

```text
Case leftist:
                <BinaryExpression> --- ||
                /                \
         <BinaryExpression>    func(1024)
         /                \
<BinaryExpression>      func(1023)
```

or,

```text
Case righist:
                <BinaryExpression> --- ||
                /                \
          func(0)                <BinaryExpression>
                                /                 \
                            func(1)               <BinaryExpression>
```

They are in equivalence relationship. With short circuit logic, we use righlist better than leftist one. Now, javaCC give us leftist syntax tree, so we must traverse whole expression tree.

Back to the title, should righlist syntax solve stack overflow? Yes, it could be used with **tail call optimization** in `eval()`

**Comment by nickl-** [comment]
Can you switch this in javacc? Where is this configured?

My first guess is that we are traversing left to right but I haven't looked at the AST in a long time so I may be mistaken.

**Comment by morris821028** [comment]
@nickl- After study some javaCC knowledge, I almost say No. Because it is a LL parser. I don't know how to make become a rightist syntax tree. But, there is a tricky Tail call optimization for your reference.

```java
// in BSHBinaryExpression.java
...
if ((kind == BOOL_AND || kind == BOOL_ANDX) && lhs == Primitive.FALSE)
	return Primitive.FALSE;
if ((kind == BOOL_OR || kind == BOOL_ORX) && lhs == Primitive.TRUE)
	return Primitive.TRUE;

if ((kind == BOOL_AND || kind == BOOL_OR) && (lhs == Primitive.FALSE || lhs == Primitive.TRUE))
	return ((SimpleNode) jjtGetChild(1)).eval(callstack, interpreter); // TCO trigger here.

Object rhs = ((SimpleNode) jjtGetChild(1)).eval(callstack, interpreter);
...
```

They can pass stack overflow problem, but it missed the test cases by `"void || false;"` or `"false || void;"` which is not in this depository. They are hard to work with TCO. 

On the other hand, we can rotate the tree before evaluation for performance. That is, extreme short-circuit logic in syntax tree. Solution maybe as follows:

```java
public Object eval(CallStack callstack, Interpreter interpreter) throws EvalError {
	if (children != null && children.length == 2 && children[0] instanceof BSHBinaryExpression) {
		BSHBinaryExpression newRoot = makeRightist(this);
		if (newRoot != this)
			return newRoot.eval(callstack, interpreter);
	}
...

private static BSHBinaryExpression makeRightist(BSHBinaryExpression curNode) {
	try {
		while (curNode != null) {
			if (curNode.children == null || curNode.children.length != 2
					|| !(curNode.children[0] instanceof BSHBinaryExpression))
				return curNode;
			int kind = curNode.kind;
			if (!(kind == BOOL_AND || kind == BOOL_OR))
				return curNode;

			BSHBinaryExpression leftNode = (BSHBinaryExpression) curNode.children[0];
			kind = leftNode.kind;
			if (!(kind == BOOL_AND || kind == BOOL_OR))
				return curNode;
			
			SimpleNode leftRightNode = (SimpleNode) leftNode.children[1];
			SimpleNode parentNode = (SimpleNode) curNode.parent;
			for (int i = 0; i < parentNode.children.length; i++) {
				SimpleNode child = (SimpleNode) parentNode.children[i];
				if (child == curNode) {
					parentNode.children[i] = leftNode;
					break;
				}
			}

			leftNode.parent = parentNode;
			leftNode.children[1] = curNode;
			curNode.children[0] = leftRightNode;
			leftRightNode.parent = curNode;

			curNode = leftNode;
		}
	} catch (Exception e) {
		e.printStackTrace();
	}
	return curNode;
}
```

**Comment by nickl-** [comment]
> They can pass stack overflow problem, but it missed the test cases by "void || false;" or "false || void;" which is not in this depository. They are hard to work with TCO.

Ox, that's a good sign then at least there is hope that we can optimise it. yeah \o/

This stuff needs another refactor I already forgot what we are trying to do here.

Are you sure the TCO happens with `checkNullValues` or is the "preserve identity semantics" also to blame?

**Comment by nickl-** [comment]
I did a refactor and added some optimisation at bd63c84f but I am afraid no matter how much we optimise there is not much we're going to accomplish with the stack usage in this use case.

It works similar to a return recursive method in the way stack memory is consumed. Every time we are required to evaluate for the right hand side (rhs) more stack space is required and the current stack allocation can only be released once that evaluation completes. 

With your limited stack size the only solution is breaking the long expression into separate statements which can complete and release allocated stack resources before evaluating the next statement. 

Alternatively stack size will need to be increased.

**Closed: Increased binary expressions incurs increased stack usage.**
