### ISSUE TITLE
When will bsh version 3.0 release?

### ISSUE THREAD

**Issue by dylan-lu** [beanshell/beanshell#561]

**Comment by nickl-** [comment]
As soon as we have completed the [road map](https://github.com/beanshell/beanshell#development-road-map), BeanShell 3.0.0 will be released.

**Comment by davide-imbriaco** [comment]
hi,
current roadmap is a little fuzzy:

> Resolve all outstanding issues and process pull requests
>  Apply uniform code style and javadocs
>  Consider feedback from community discussions

this could take some months or some years. Do you have some kind of estimate date (even if it is very rough, such as "in the next 2 to 4 months" or "not before next summer")? 

Thank you,
D

**Comment by nickl-** [comment]
Also from the README

> Most of the outstanding issues were imported from sourceforge, reported many years ago and now orphaned without owners. The majority will already be resolved in master, the valid ones need to be identified to the developers. An earnest call goes out for assistance in processing these issues to verify if they are still valid, reproducible or already resolved.

**Comment by skyghis** [comment]
Hi @nickl- 

Why not release in maven central a `3.0.0-alpha-0` to ease testing and help new comers to jump-in ?

History behind this proposition :

I am actually searching a solution to replace deprecated Nashorn with a lightweight alternative, and Beanshell seem interesting. But the last release in Maven central is `v2.0b6` from Feb 2016 and in my company, and probably many others, I can't add dependencies from code source into our build pipeline.

Actually if I want to use bsh, I have to use `v2.0b6` witch is no longer supported and probably incompatible with future `3.x` versions.

**Comment by opeongo** [comment]
Looking over the road map in the project README it looks like we are pretty close.

I think it would be helpful to triage and make a list of showstoppers on the way to a 3.0.0 release.  Most of the backlog of bug reports ported forward from SourceForge and not relevant, but I will take some time and go through and review and sort them in to piles of urgent and non-urgent.

A quick look from my point of view seems like #505 and #508 are real problems, certainly they are preventing me from using this development BeanShell version as my internal daily driver.

**Comment by stain** [comment]
OK, so we've got a couple of [pull requests](https://github.com/beanshell/beanshell/pulls) open still (most from @opeongo actually, would someone help review those?)

Not wanting to require those I think we can release now the master as `3.0-alpha-1` under `org.beanshell` - then we try to get `3.0.0` out after reviewing/merging those PRs.

**Comment by opeongo** [comment]
I think that there are a couple of show stoppers in the code still that would preclude making an alpha release at this moment.  #508 seems to point to something wrong that may have impacts elsewhere.  Perhaps there are other show stoppers as well.

Otherwise, I agree that it would be a good idea to have a feature freeze and get a release rolling.

**Comment by nickl-** [comment]
I have acquired access to sonatype so we can do snap shot releases in the interim.

@stain I sent you the details and noticed some commits to master, what did you manage to accomplish in this regard?

**Comment by yonigibbs** [comment]
Is there an update on an ETA for v3.0? We specifically need the check for the thread being interrupted (see [here](https://github.com/beanshell/beanshell/blob/master/src/main/java/bsh/Interpreter.java#L490)) which will allow us to trap accidental infinite loops in script files by interrupting the thread.

Also we're a bit unclear about this bit in the readme:

> The only reccomended version is a manual build of the master branch. Support for legacy releases reached end of line

Does that mean that older versions are no longer supported? Should we just manually build the latest code from the master branch and drop that JAR into our product? Or is the code not in a ready state for that?

Thanks!

**Comment by nickl-** [comment]
The BeanShell 3.0 SNAPSHOT release should now be available under:

groupId: org.beanshell
artifactId: bsh

nJoy!

**Comment by opeongo** [comment]
You released a snapshot with issue #590 still unresolved?  Are you not concerned that this known fundamental bug will cause people to lose confidence in the project? 

Your obstinacy on this issue is remarkable.  This isn't even about whether the fix that I proposed fixes the bug (it does).  What is this about?

**Comment by nickl-** [comment]
It is just that, a SNAPSHOT (or under development) release, all known issues remain, in fact it may not even be useful at all and building from master is still preferable.

We have tried the approach of holding back releases to urge the community to get involved. **That didn't work!**

All it did accomplish was to generate new issues requesting a release. Frustrating me for repeatedly having to explain the same thing, further having to beg for assistance, and being told I should chill. So if for nothing else this is being released for my own peace of mind and increased chill factor =)

> You released a snapshot with issue #590 still unresolved? Are you not concerned that this known fundamental bug will cause people to lose confidence in the project?

Anyone stumbling across an issue of operator precedence will quickly realize that using brackets is the work around, even without having to consult documentation or the issue queue, so is it really so fundamental that you will loose confidence? I did consider it but thank you for raising the concern.

#590 is still a priority, along with the other outstanding [parser issues](https://github.com/beanshell/beanshell/labels/Parsing) and will be dealt with. However for this week the tedious and unrewarding task of sorting through the backlog takes precedence. Any help and assistance will be greatly appreciated.

Instead of doing the same thing lets try something else expecting different results.

**Comment by nickl-** [comment]
Closed snap shot release made
