### ISSUE TITLE
Question: Is it not dead?

### ISSUE THREAD

**Issue by netbeansuser2019** [beanshell/beanshell#584]
Sorry to say, but I think that it should be no more waiting for release as common picture to me and I guess even to others if there is missing a release for long time that project is dead.

Especially as there are broken links on "readme page" and mentioned "next release will be a production ready major version" so that sounds like that there is no such release and such library is just for fan.

I would like to suggest to be released as soon as and then setup a cycle as e.g. Oracle with Java.

Frankly speaking there is even no roadmap even it is called as that, but it is not a roadmap to me as there is no "when/frequency a year".

**Comment by drosenbauer** [comment]
I agree, let's at least tag a recent build as a release candidate, so it's clear that something is coming.

**Comment by jaydeepmehta15** [comment]
@nickl- Do find it as open Issue. Request to close this. 

Beanshell is widely used in many major open source as well as commercial projects. Looking forward for production release

**Comment by nickl-** [comment]
The [roadmap](https://github.com/beanshell/beanshell#development-road-map) is dependent on the community assisting to work through the backlog of ownerless issues imported from sourceforge. Since the current base is a merge of all forks we really need to go through the outstanding issues or they will remain open indefinitely.

There has been very little progress in this regard. If everyone just does one issue per week we would've been done by now.

Once 3.0 is released we can consider shorter release cycles.

**Closed: follow roadmap to release**
