### ISSUE TITLE
Any upcoming releases?

### ISSUE THREAD

**Issue by jimjag** [beanshell/beanshell#594]
There are some projects currently dependent on 2.0b6 but would like to make the effort to upgrade to the latest version; However, the new version's refactoring makes the upgrade non-trivial, especially without a formal release under the new structure. Is a release expected anytime soon?

**Comment by VVD** [comment]
Can't build 2.0b6 with Java 11.
But I see version in git support Java 11+.
What about just create tag 3.0a1 or something like this?

**Comment by pgiffuni** [comment]
We really need fresh blood in Beanshell. jimjag@ want to join?

**Comment by slachiewicz** [comment]
what is the latest available 2.x release? From Github Release we have 2.1 but 2.1 isn't available on Maven Central

**Comment by opeongo** [comment]
Is anyone still participating in this project have maintainer/commit privileges?  I'm not seeing a lot of action here.  I have a PR in the queue that is over 2 years old.

**Comment by leginee** [comment]
Okay, if I want to help. Where do I start?

**Comment by opeongo** [comment]
@pgiffuni, @nickl- , @stain , @stefanofornari or any one of the other maintainers of this project.  Can you add me as a maintainer so that I can apply some of the pull requests and get a release out?

**Comment by nickl-** [comment]
Seriously another duplicate!?!?!?! #603 and #561 The information you seek and the remedy is even published on the project home page. Not even 1 of the outstanding issues has had any attention whatsoever. 

@opeongo 
> @pgiffuni, @nickl- , @stain , @stefanofornari or any one of the other maintainers of this project. Can you add me as a maintainer so that I can apply some of the pull requests and get a release out?

Already done but that was for your tenacity and hard work, not because of these demands. Was it a mistake?

To make this clear:

WE WILL NOT RELEASE BEANSHELL 3.0 BEFORE THE OUTSTANDING ISSUES ARE RESOLVED **BY THE COMMUNITY**

**Closed: duplicate and it leaves a bad taste in ones mouth**

As per #603:

> I will not respond to further comments on this thread again, if you are keen to see a release you know what to do. See you on the outstanding issues, and we consider it a clean sheet.

**Comment by opeongo** [comment]
Hey @nickl, don't take this the wrong way.  No one intended any malice.  I think the posts in this issue reflect the concerns of members of the user community after not seeing any action for over a year.  Certainly from my point of view I could just fork and go my own way, but I want the community to thrive.  It's the law of the web that sometimes software projects get orphaned, and without any updates for a long time people (including me) were getting concerned.  I reached out to ask for maintainer privileges so that I could help to keep the project active, and I did not mean any offence or to leave a bad taste.

**Comment by nickl-** [comment]
Water under the bridge, no hard feelings. Hope the feeling is mutual.

Got upset because it has been more than 2 years (according to git) since the call for assistance with the backlog of issues was made on the readme.md and no one has answered the call. But when it comes to our time... anyway. Lost my temper and that's not cool. Apologies to everyone!
