### ISSUE TITLE
DEBUG property per instance

### ISSUE THREAD

**Issue by max-m-s** [beanshell/beanshell#638]
An application could have multiple Interpreters running. But since the DEBUG property is static, you can only enable it for the whole lot.
Could we have a debug property per instance?

**Comment by nickl-** [comment]
I believe the debug messages are passed statically using `Interpreter.debug` since there isn't necessarily a reference to the interpreter everywhere debug information is generated. It will then require that the flag also be static as the message also has no instance to query.

Perhaps if we separate this and implement a debug logger, the interpreter could choose to enable it, but that will be a major change.

**Comment by nickl-** [comment]
We are using a thread local flag now so there is an extend to which interpreters can be separately debugged, it as far as they are isolated on separate threads.

Closing: compromise reached
