### ISSUE TITLE
How to get the status of the parser... (wrt BshConsole/promot)

### ISSUE THREAD

**Issue by stefanofornari** [beanshell/beanshell#70]
Hey,

I have a clear understanding of why the prompt is not correctly managed in BshConsole. Basicall, I am setting the prompt by bsh.prompt, which is managed by beanshell. This works well for mult-line statements too because Bsh knows not to print the prompt in the middle of a statement. However, because jline does not know about it, when you delete the first character after the prompt, it rewrites the entire line, which from its perspective is empty. The result is that the prompt disappears.

The solution should be that when I read a line from jline, I can tell it to use or not the prompt (or which prompt). To do so, I would need a way to know in which state the parser is. Is there any ways to know that? Or shall I instead look into the grammar and propose a way to expose the status of the parser?

I'd like to implement something like this:

Interpreter bsh = ... ;

if (bsh.isInStatement()) {
  line = jline.readLine();
} else {
  line = jline.readLine(prompt);
}

thanks in advance,
Stefano

**Comment by nickl-** [comment]
I am not sure what parser status you are looking for. The magic all happens in the eval REPL loop in `Interpreter`, which pulls nodes from the parser and evaluates them. 

The parser populates `Line()` which if false indicate `EOF' so there is no waiting for the parser to complete work instead we are pulling the information from it. 

 This is the REPL loop, pay attention to `SimpleNode` which is produced by the parser.

https://github.com/beanshell/beanshell/blob/99e392e3fdf45e39fbb8c327ca02604ff529249c/src/main/java/bsh/Interpreter.java#L476-L521

Hope this helps...

**Comment by nickl-** [comment]
@stefanofornari was this any help? Perhaps I don't quite understand what you are looking for exactly, could you elaborate?

**Comment by nickl-** [comment]
I don't think `bsh.isInStatement` ever, the input is funnelled through `Reader Interpreter.in` which goes straight to the parser `public Parser(java.io.Reader stream)` and we get nodes out. 

Not sure the parser even knows where it is at any given point, it only knows what token it's on and depending on lookahead how many tokens it looks at in front. a Token is generally considered a single character. So you see what I mean... I doubt it knows it is in a class block after it created the class declaration node.

Nothing stops you from holding the lines in jline, until block is finished and then sending it to bsh. Ol is this the question: How do we know we are in a block?

Well I would assume you can look and count the begins `{` and wait and count till you have all the ends `}` maybe? That is all that is considered a block. Otherwise you can go bf line and wait for line terminator `;` maybe.

**Comment by stefanofornari** [comment]
@nickl- , thanks for your inputs. the code you pointed out at the beginning shed some light and I found a way. maybe not the best option, but it works: basically, beanshell asks for a prompt calling getBshPrompt() only when a statement has been consumed. in the middle of a multiline statement getBshPrompt() is not called.
Therefore I redefined getBshPrompt() to inject the prompt into jline reader. Together with cleaning the jline reader prompt on a new line made the trick.
The only drawback I see is that getBshPrompt() shall not be freely redefined. But you can still use bsh.prompt to set your own prompt.

thanks a lot for your help.

**Comment by nickl-** [comment]
As it turns out `;` is a valid node `EmptyStatement` which the parser ignores. Beanshell correctly identifies that you are in a block and refrains from sending a prompt again in multi line mode.
